require: rubocop-sketchup

inherit_from: sketchup-style.yml

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
    - 'tools/**/*'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true


# Need to explicitly disable the SketchUp cops here because Rake tasks will
# load the gem and cause them to be run.
# (Not sure why DisabledByDefault isn't enough.)

SketchupDeprecations:
  Enabled: false

SketchupPerformance:
  Enabled: false

SketchupRequirements:
  Enabled: false

SketchupSuggestions:
  Enabled: false


Layout/AlignArray:
  Exclude:
    - spec/**/*

Layout/AlignParameters:
  Exclude:
    - spec/**/*

Layout/IndentationConsistency:
  Exclude:
    - spec/**/*


Lint/InterpolationCheck:
  Exclude:
    - spec/rubocop/sketchup/cop/requirements/observers_start_operation_spec.rb


Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - tools/stdlib_scraper.rb

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/sketchup/formatter/extension_review.rb
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - lib/rubocop/sketchup/cop/suggestions/operation_name.rb
    - spec/**/*
    - tools/**/*

Metrics/MethodLength:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/file_structure.rb
    - lib/rubocop/sketchup/cop/requirements/sketchup_extension.rb
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - lib/rubocop/sketchup/dc_methods.rb
    - lib/rubocop/sketchup/features.rb


Style/MultilineBlockChain:
  Exclude:
    - lib/rubocop/sketchup/formatter/extension_review.rb

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - spec/**/*
