require: rubocop-sketchup

AllCops:
  DisabledByDefault: true # TODO: Enable after configuring.
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
    - 'tools/**/*'
  Exclude:
    - 'bin/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true


# Need to explicitly disable the SketchUp cops here because Rake tasks will
# load the gem and cause them to be run.
# (Not sure why DisabledByDefault isn't enough.)

SketchupDeprecations:
  Enabled: false

SketchupPerformance:
  Enabled: false

SketchupRequirements:
  Enabled: false

SketchupSuggestions:
  Enabled: false
