require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-sketchup

inherit_from: sketchup-style.yml

plugins:
  - rubocop-rspec

AllCops:
  # RuboCop 1.x uses semantic versioning. However, to avoid the CI build from
  # breaking when a new cop is added that might yield warnings new cops are
  # kept disabled and instead enabled explicitly as new versions are tested.
  # NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'examples/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.6


# Need to explicitly disable the SketchUp cops here because Rake tasks will
# load the gem and cause them to be run.
# (Not sure why DisabledByDefault isn't enough.)

SketchupBugs:
  Enabled: false

SketchupDeprecations:
  Enabled: false

SketchupPerformance:
  Enabled: false

SketchupRequirements:
  Enabled: false

SketchupSuggestions:
  Enabled: false


Gemspec/AddRuntimeDependency: # new in 1.65
  Enabled: true

Gemspec/AttributeAssignment: # new in 1.77
  Enabled: true

Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true

Gemspec/DeprecatedAttributeAssignment: # new in 1.10
  Enabled: true

Gemspec/RequireMFA: # new in 1.23
  Enabled: false


Layout/ArrayAlignment:
  Exclude:
    - spec/**/*

Layout/AssignmentIndentation:
  Exclude:
    - tasks/cops_documentation.rake

Layout/EmptyLinesAfterModuleInclusion: # new in 1.79
  Enabled: true

Layout/FirstArgumentIndentation:
  Exclude:
    - tasks/**/*

Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true

Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true

Layout/LineLength:
  Max: 80
  Exclude:
    - lib/rubocop/sketchup/cop/suggestions/operation_name.rb
    - spec/**/*
    - tasks/**/*
    - tools/**/*

Layout/IndentationConsistency:
  Exclude:
    - spec/**/*

Layout/ParameterAlignment:
  Exclude:
    - spec/**/*
    - tasks/**/*

Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true


Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/ArrayLiteralInRegexp: # new in 1.71
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/BooleanSymbol:
  Exclude:
    - lib/rubocop/sketchup/cop/deprecations/operation_next_transparent.rb

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true

Lint/ConstantReassignment: # new in 1.70
  Enabled: true

Lint/CopDirectiveSyntax: # new in 1.72
  Enabled: true

Lint/DeprecatedConstants: # new in 1.8
  Enabled: true

Lint/DuplicateBranch: # new in 1.3
  Enabled: true

Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # new in 1.1
  Enabled: true

Lint/DuplicateSetElement: # new in 1.67
  Enabled: true

Lint/EmptyBlock: # new in 1.1
  Enabled: true

Lint/EmptyClass: # new in 1.3
  Enabled: true

Lint/EmptyInPattern: # new in 1.16
  Enabled: true

Lint/HashNewWithKeywordArgumentsAsDefault: # new in 1.69
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true

Lint/InterpolationCheck:
  Exclude:
    - spec/rubocop/sketchup/cop/requirements/observers_start_operation_spec.rb

Lint/LambdaWithoutLiteralBlock: # new in 1.8
  Enabled: true

Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # new in 1.2
  Enabled: true

Lint/NumberedParameterAssignment: # new in 1.9
  Enabled: true

Lint/NumericOperationWithConstantResult: # new in 1.69
  Enabled: true

Lint/OrAssignmentToConstant: # new in 1.9
  Enabled: true

Lint/RedundantDirGlobSort: # new in 1.8
  Enabled: true

Lint/RedundantTypeConversion: # new in 1.72
  Enabled: true

Lint/RefinementImportMethods: # new in 1.27
  Enabled: true

Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true

Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true

Lint/SharedMutableDefault: # new in 1.70
  Enabled: true

Lint/SuppressedExceptionInNumberConversion: # new in 1.72
  Enabled: true

Lint/SymbolConversion: # new in 1.9
  Enabled: true

Lint/ToEnumArguments: # new in 1.1
  Enabled: true

Lint/TripleQuotes: # new in 1.9
  Enabled: true

Lint/UnescapedBracketInRegexp: # new in 1.68
  Enabled: true

Lint/UnexpectedBlockArity: # new in 1.5
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # new in 1.1
  Enabled: true

# Disabled as while the constant won't be private, it's more readable sometimes
# to define the constant close to where it is used. No need to switch scopes
# just for that.
Lint/UselessConstantScoping: # new in 1.72
  Enabled: false

Lint/UselessDefaultValueArgument: # new in 1.76
  Enabled: true

Lint/UselessDefined: # new in 1.69
  Enabled: true

Lint/UselessNumericOperation: # new in 1.66
  Enabled: true

Lint/UselessOr: # new in 1.76
  Enabled: true

Lint/UselessRescue: # new in 1.43
  Enabled: true

Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true

Lint/ItWithoutArgumentsInBlock: # new in 1.59
  Enabled: true

Lint/LiteralAssignmentInCondition: # new in 1.58
  Enabled: true

Lint/MixedCaseRange: # new in 1.53
  Enabled: true

Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true


Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - tasks/cops_documentation.rake
    - tasks/cut_release.rake
    - tools/stdlib_scraper.rb

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/ruby_core_namespace.rb
    - lib/rubocop/sketchup/cop/requirements/ruby_stdlib_namespace.rb
    - lib/rubocop/sketchup/formatter/extension_review.rb
    - spec/**/*
    - tasks/cops_documentation.rake

Metrics/CollectionLiteralLength: # new in 1.47
  Enabled: true
  Exclude:
    - lib/rubocop/sketchup/features.rb

Metrics/MethodLength:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/file_structure.rb
    - lib/rubocop/sketchup/cop/requirements/sketchup_extension.rb
    - tasks/**/*
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - lib/rubocop/sketchup/dc_methods.rb
    - lib/rubocop/sketchup/features.rb


Naming/BlockForwarding: # new in 1.24
  Enabled: true

Naming/FileName:
  Exclude:
    - lib/rubocop-sketchup.rb # Not changing the name now.

# Just because a method returns a boolean, doesn't mean it should be a predicate.
# If it has side effects, it shouldn't need the `?` suffix.
Naming/PredicateMethod: # new in 1.76
  Enabled: false

# When performance isn't critical, computing sizes avoid magic numbers that
# might get out of sync.
Performance/FixedSize:
  Exclude:
    - tasks/cops_documentation.rake

# What this cop suggests makes the code less intuitive/readable.
# Keeping it disabled until there's a known tangible performance impact for this
# gem.
Performance/UnfreezeString:
  Enabled: false

Performance/AncestorsInclude: # new in 1.7
  Enabled: true

Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: true

Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: true

Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: true

Performance/ConstantRegexp: # new in 1.9
  Enabled: true

Performance/MapCompact: # new in 1.11
  Enabled: true

# Doing the changes suggested cause a false positive in
# Lint/DeprecatedClassMethods related to `iterator?(arg)`. Disabling for now.
# Can revisit later. Not sure how much impact this has to be worth it.
Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: false

Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: true

Performance/RedundantSortBlock: # new in 1.7
  Enabled: true

Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: true

Performance/RedundantStringChars: # new in 1.7
  Enabled: true

Performance/ReverseFirst: # new in 1.7
  Enabled: true

Performance/SortReverse: # new in 1.7
  Enabled: true

Performance/Squeeze: # new in 1.7
  Enabled: true

Performance/StringInclude: # new in 1.7
  Enabled: true

Performance/Sum: # new in 1.8
  Enabled: true


RSpec/BeEq: # new in 2.9.0
  Enabled: true

RSpec/BeNil: # new in 2.9.0
  Enabled: true

RSpec/ChangeByZero: # new in 2.11
  Enabled: true

# Too many cases of nested context where this rule doesn't apply.
RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/project_spec.rb # Not testing a class/module.

RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true

RSpec/ExampleLength:
  Max: 20

RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true

# RSpec/FilePath:
#   CustomTransform:
#     DynamicComponentInternals: dc_internals
#     OpenSSL: openssl
#     RubyStdLibNamespace: ruby_stdlib_namespace
#     SketchUp: sketchup
#     SketchUpTargetRange: sketchup_target_range

RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true

RSpec/IncludeExamples: # new in 3.6
  Enabled: true

# TODO: Cleanup. Enable after fixing existing issues.
RSpec/LeakyLocalVariable: # new in 3.8
  Enabled: false

RSpec/NoExpectationExample: # new in 2.13
  Enabled: true

RSpec/Output: # new in 3.9
  Enabled: true

RSpec/PendingWithoutReason: # new in 2.16
  Enabled: true

RSpec/RedundantAround: # new in 2.19
  Enabled: true

RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true

RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true

RSpec/SortMetadata: # new in 2.14
  Enabled: true

RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true

RSpec/BeEmpty: # new in 2.20
  Enabled: true

RSpec/ContainExactly: # new in 2.19
  Enabled: true

RSpec/EmptyMetadata: # new in 2.24
  Enabled: true

RSpec/Eq: # new in 2.24
  Enabled: true

RSpec/IndexedLet: # new in 2.20
  Enabled: true

RSpec/IsExpectedSpecify: # new in 2.27
  Enabled: true

RSpec/MatchArray: # new in 2.19
  Enabled: true

RSpec/MetadataStyle: # new in 2.24
  Enabled: true

RSpec/ReceiveMessages: # new in 2.23
  Enabled: true

RSpec/RedundantPredicateMatcher: # new in 2.26
  Enabled: true

RSpec/RemoveConst: # new in 2.26
  Enabled: true

RSpec/RepeatedSubjectCall: # new in 2.27
  Enabled: true

RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: false # Not renaming all the files at this point.

RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: true


Security/CompoundHash: # new in 1.28
  Enabled: true

Security/IoMethods: # new in 1.22
  Enabled: true


Style/AmbiguousEndlessMethodDefinition: # new in 1.68
  Enabled: true

Style/ArgumentsForwarding: # new in 1.1
  Enabled: true

Style/ArrayIntersect: # new in 1.40
  Enabled: true

Style/ArrayIntersectWithSingleElement: # new in 1.81
  Enabled: true

Style/BitwisePredicate: # new in 1.68
  Enabled: true

Style/ClassVars:
  Exclude:
    - lib/rubocop/sketchup/cop/requirements/extension_namespace.rb
    - lib/rubocop/sketchup/cop/requirements/file_structure.rb

Style/CollectionCompact: # new in 1.2
  Enabled: true

Style/CollectionQuerying: # new in 1.77
  Enabled: true

Style/ComparableClamp: # new in 1.44
  Enabled: true

Style/CombinableDefined: # new in 1.68
  Enabled: true

Style/ComparableBetween: # new in 1.74
  Enabled: true

Style/ConcatArrayLiterals: # new in 1.41
  Enabled: true

Style/DigChain: # new in 1.69
  Enabled: true

Style/DocumentDynamicEvalDefinition: # new in 1.1
  Enabled: true

Style/DirEmpty: # new in 1.48
  Enabled: true

Style/EmptyClassDefinition: # new in 1.83
  Enabled: true

Style/EmptyHeredoc: # new in 1.32
  Enabled: true

Style/EmptyStringInsideInterpolation: # new in 1.76
  Enabled: true

Style/EndlessMethod: # new in 1.8
  Enabled: true

Style/EnvHome: # new in 1.29
  Enabled: true

Style/FetchEnvVar: # new in 1.28
  Enabled: true

Style/FileNull: # new in 1.69
  Enabled: true

Style/FileTouch: # new in 1.69
  Enabled: true

# The `expect_no_offenses` and `expect_no_offenses` special assertions have
# custom formatting directives. They will however trigger this cop.
Style/FormatStringToken:
  AllowedMethods:
    - expect_offense
    - expect_no_offenses

Style/FileEmpty: # new in 1.48
  Enabled: true

Style/FileRead: # new in 1.24
  Enabled: true

Style/FileWrite: # new in 1.24
  Enabled: true

Style/HashConversion: # new in 1.10
  Enabled: true

Style/HashExcept: # new in 1.7
  Enabled: true

Style/HashFetchChain: # new in 1.75
  Enabled: true

Style/HashSlice: # new in 1.71
  Enabled: true

Style/IfWithBooleanLiteralBranches: # new in 1.9
  Enabled: true

Style/InPatternThen: # new in 1.16
  Enabled: true

Style/ItAssignment: # new in 1.70
  Enabled: true

Style/ItBlockParameter: # new in 1.75
  Enabled: true

Style/KeywordArgumentsMerging: # new in 1.68
  Enabled:

Style/MapIntoArray: # new in 1.63
  Enabled: true

Style/ModuleMemberExistenceCheck: # new in 1.82
  Enabled: true

Style/NegativeArrayIndex: # new in 1.83
  Enabled: true

Style/ObjectThen: # new in 1.28
  Enabled: true

Style/OperatorMethodCall: # new in 1.37
  Enabled: true

Style/MagicCommentFormat: # new in 1.35
  Enabled: true

Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true

Style/MapToHash: # new in 1.24
  Enabled: true

Style/MapToSet: # new in 1.42
  Enabled: true

Style/MinMaxComparison: # new in 1.42
  Enabled: true

Style/MultilineBlockChain:
  Exclude:
    - lib/rubocop/sketchup/formatter/extension_review.rb

Style/MultilineInPatternThen: # new in 1.16
  Enabled: true

Style/NegatedIfElseCondition: # new in 1.2
  Enabled: true

Style/NestedFileDirname: # new in 1.26
  Enabled: true

Style/NilLambda: # new in 1.3
  Enabled: true

Style/NumberedParameters: # new in 1.22
  Enabled: true

Style/NumberedParametersLimit: # new in 1.22
  Enabled: true

Style/OpenStructUse: # new in 1.23
  Enabled: true
  Exclude:
    - lib/rubocop/sketchup/formatter/extension_review.rb

Style/QuotedSymbols: # new in 1.16
  Enabled: true

Style/RedundantArrayFlatten: # new in 1.76
  Enabled: true

Style/RedundantConstantBase: # new in 1.40
  Enabled: true

Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true

Style/RedundantEach: # new in 1.38
  Enabled: true

Style/RedundantFormat: # new in 1.72
  Enabled: true

Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: true

Style/RedundantInitialize: # new in 1.27
  Enabled: true

Style/RedundantInterpolationUnfreeze: # new in 1.66
  Enabled: true

Style/RedundantReturn:
  Exclude:
  - lib/rubocop/sketchup/cop/requirements/sketchup_require.rb # Nit picking.

Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true

Style/RedundantStringEscape: # new in 1.37
  Enabled: true

Style/ReverseFind: # new in 1.83
  Enabled: true

Style/SafeNavigationChainLength: # new in 1.68
  Enabled: true

Style/SelectByRegexp: # new in 1.22
  Enabled: true

Style/SendWithLiteralMethodName: # new in 1.64
  Enabled: true

Style/StringChars: # new in 1.12
  Enabled: true

Style/SuperArguments: # new in 1.64
  Enabled: true

Style/SwapValues: # new in 1.1
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - spec/**/*
    - tasks/cops_documentation.rake

Style/DataInheritance: # new in 1.49
  Enabled: true

Style/ExactRegexpMatch: # new in 1.51
  Enabled: true

Style/RedundantArrayConstructor: # new in 1.52
  Enabled: true

Style/RedundantCurrentDirectoryInPath: # new in 1.53
  Enabled: true

Style/RedundantFilterChain: # new in 1.52
  Enabled: true

Style/RedundantLineContinuation: # new in 1.49
  Enabled: true

Style/RedundantRegexpArgument: # new in 1.53
  Enabled: true

Style/RedundantRegexpConstructor: # new in 1.52
  Enabled: true

Style/ReturnNilInPredicateMethodDefinition: # new in 1.53
  Enabled: true

Style/SingleLineDoEndBlock: # new in 1.57
  Enabled: true

Style/SuperWithArgsParentheses: # new in 1.58
  Enabled: true

Style/YAMLFileRead: # new in 1.53
  Enabled: true
