# frozen_string_literal: true

module RuboCop
  module Cop
    module SketchupRequirements
      class RubyCoreNamespace < Cop

        include NoCommentDisable
        include Sketchup::NamespaceChecker

        MSG = 'Do not modify Ruby core functionality.'.freeze

        NAMESPACES_RUBY_186 = %w(
          ArgumentError
          Array
          Bignum
          Binding
          Class
          Comparable
          Continuation
          Data
          Dir
          EOFError
          Enumerable
          Errno
          Exception
          FalseClass
          File
          File::Constants
          File::Stat
          FileTest
          Fixnum
          Float
          FloatDomainError
          GC
          Hash
          IO
          IOError
          IndexError
          Integer
          Interrupt
          Kernel
          LoadError
          LocalJumpError
          Marshal
          MatchData
          Math
          Method
          Module
          NameError
          NameError::message
          NilClass
          NoMemoryError
          NoMethodError
          NotImplementedError
          Numeric
          Object
          ObjectSpace
          Precision
          Proc
          Process
          Process::GID
          Process::Status
          Process::Sys
          Process::UID
          Range
          RangeError
          Regexp
          RegexpError
          RuntimeError
          ScriptError
          SecurityError
          Signal
          SignalException
          StandardError
          String
          Struct
          Symbol
          SyntaxError
          SystemCallError
          SystemExit
          SystemStackError
          Thread
          ThreadError
          ThreadGroup
          Time
          TrueClass
          TypeError
          UnboundMethod
          ZeroDivisionError
        ).freeze

        NAMESPACES_RUBY_200 = %w(
          ARGF
          ArgumentError
          Array
          BasicObject
          Bignum
          Binding
          Class
          Comparable
          Complex
          Continuation
          Data
          Dir
          ENV
          EOFError
          Encoding
          Encoding::CompatibilityError
          Encoding::Converter
          Encoding::ConverterNotFoundError
          Encoding::InvalidByteSequenceError
          Encoding::UndefinedConversionError
          EncodingError
          Enumerable
          Enumerator
          Enumerator::Generator
          Enumerator::Lazy
          Enumerator::Yielder
          Errno
          Exception
          FalseClass
          Fiber
          FiberError
          File
          File::Constants
          File::Stat
          FileTest
          Fixnum
          Float
          FloatDomainError
          GC
          GC::Profiler
          Hash
          IO
          IO::WaitReadable
          IO::WaitWritable
          IOError
          IndexError
          Integer
          Interrupt
          Kernel
          KeyError
          LoadError
          LocalJumpError
          Marshal
          MatchData
          Math
          Math::DomainError
          Method
          Module
          Mutex
          NameError
          NilClass
          NoMemoryError
          NoMethodError
          NotImplementedError
          Numeric
          Object
          ObjectSpace
          ObjectSpace::WeakMap
          Proc
          Process
          Process::GID
          Process::Status
          Process::Sys
          Process::UID
          Random
          Range
          RangeError
          Rational
          Rational::compatible
          Regexp
          RegexpError
          RubyVM
          RubyVM::Env
          RubyVM::InstructionSequence
          RuntimeError
          ScriptError
          SecurityError
          Signal
          SignalException
          StandardError
          StopIteration
          String
          Struct
          Symbol
          SyntaxError
          SystemCallError
          SystemExit
          SystemStackError
          Thread
          Thread::Backtrace
          Thread::Backtrace::Location
          ThreadError
          ThreadGroup
          Time
          TracePoint
          TrueClass
          TypeError
          UnboundMethod
          ZeroDivisionError
        ).freeze

        NAMESPACES_RUBY_220 = %w(
          ArgumentError
          Array
          BasicObject
          Bignum
          Binding
          Class
          Comparable
          Complex
          ConditionVariable
          Continuation
          Data
          Dir
          ENV
          EOFError
          Encoding
          Encoding::CompatibilityError
          Encoding::Converter
          Encoding::ConverterNotFoundError
          Encoding::InvalidByteSequenceError
          Encoding::UndefinedConversionError
          EncodingError
          Enumerable
          Enumerator
          Enumerator::Generator
          Enumerator::Lazy
          Enumerator::Yielder
          Errno
          Exception
          FalseClass
          Fiber
          FiberError
          File
          File::Constants
          File::Stat
          FileTest
          Fixnum
          Float
          FloatDomainError
          GC
          GC::Profiler
          Hash
          IO
          IO::EAGAINWaitReadable
          IO::EAGAINWaitWritable
          IO::EINPROGRESSWaitReadable
          IO::EINPROGRESSWaitWritable
          IO::EWOULDBLOCKWaitReadable
          IO::EWOULDBLOCKWaitWritable
          IO::WaitReadable
          IO::WaitWritable
          IOError
          IndexError
          Integer
          Interrupt
          Kernel
          KeyError
          LoadError
          LocalJumpError
          Marshal
          MatchData
          Math
          Math::DomainError
          Method
          Module
          Mutex
          NameError
          NilClass
          NoMemoryError
          NoMethodError
          NotImplementedError
          Numeric
          Object
          ObjectSpace
          ObjectSpace::WeakMap
          Proc
          Process
          Process::GID
          Process::Status
          Process::Sys
          Process::UID
          Process::Waiter
          Queue
          Random
          Range
          RangeError
          Rational
          Rational::compatible
          Regexp
          RegexpError
          RubyVM
          RubyVM::Env
          RubyVM::InstructionSequence
          RuntimeError
          ScriptError
          SecurityError
          Signal
          SignalException
          SizedQueue
          StandardError
          StopIteration
          String
          Struct
          Symbol
          SyntaxError
          SystemCallError
          SystemExit
          SystemStackError
          Thread
          Thread::Backtrace
          Thread::Backtrace::Location
          ThreadError
          ThreadGroup
          Time
          TracePoint
          TrueClass
          TypeError
          UnboundMethod
          UncaughtThrowError
          ZeroDivisionError
        ).freeze

        NAMESPACES = ((
          NAMESPACES_RUBY_186 |
          NAMESPACES_RUBY_200 |
          NAMESPACES_RUBY_220
        ) - ['Object']).freeze
        # This checks ignores items added to 'Object' as that is considered
        # global namespace and have separate cops for that.

        def namespaces
          NAMESPACES
        end

      end
    end
  end
end
